mingestibles/RGD/gene-to-phenotype.py
mingestibles/RGD/gene-to-phenotype.yaml
mingestibles/RGD/metadata.yaml
mingestibles/maps/rgd-gene.yaml

using alliance import file, with a gpi map used to subset to only gene annotations

RGD g2p load 

---

.github/workflows/test.yml
mingestibles/pombase/gene2phenotype.yaml
mingestibles/rgd/gene2phenotype.py
mingestibles/xenbase/gene2phenotype.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_mingestibles.py
tests/unit/pombase/test_pombase_gene2phenotype.py
tests/unit/rgd/test_rgd_gene2phenotype.py
tests/unit/xenbase/test_xenbase_gene2phenotype.py
tests/unit/xenbase/test_xenbase_gene_information.py
tests/unit/xenbase/test_xenbase_gene_literature.py

Some initial tests in place, they're so similar that they could probably be shared at this point, but with more complex ingests there will be a chance to beef up the testing I'm sure.

Ingest unit tests

---

mingestibles/maps/eqe2zp.yaml
mingestibles/rgd/gene2phenotype.yaml
mingestibles/zfin/gene2phenotype.py
mingestibles/zfin/gene2phenotype.yaml
mingestibles/zfin/metadata.yaml
tests/conftest.py
tests/unit/zfin/test_zfin_gene2phenotype.py

I'm definitely still trying different approaches to how to test the transform code against different sorts of data. I think I'm getting closer to figuring out the right mix of pre-defined fixtures and parameterization, but the two approaches don't quite seem to intersect as well as I'd like.

ZFIN g2p load from "clean genes" file, with tests

---

Makefile
merge.yaml
poetry.lock

I can imagine that we eventually might want to generate this file dynamically, but for now here's a static version.
Closes #11

Added a merge.yaml for kgx merging

---

monarch_ingest/alliance/gene2phenotype.yaml
monarch_ingest/alliance/gene_information.yaml
source_template/source-file-template-json.yaml

I set the required properties (that we can currently handle) in the source_file config for the Alliance BGI & G2P loads
closes #21

Added required properties for the two JSON based ingests

---

.github/workflows/test.yml
Makefile
docs/index.md
docs/ingests/alliance.md
docs/ingests/pombase.md
docs/ingests/xenbase.md
docs/ingests/zfin.md
docs/tutorials/add-documentation.md
docs/tutorials/configure-ingest.md
docs/tutorials/implement-ingest.md
docs/tutorials/validate-output.md
merge.yaml
mkdocs.yml
monarch_ingest/alliance/gene2disease.py
monarch_ingest/alliance/gene2disease.yaml
monarch_ingest/alliance/metadata.yaml
poetry.lock
pyproject.toml
source_template/test_somethingbase_template.py

A little bit of a weird combo PR, but I wanted an ingest to do while writing the tutorial.

Tutorial doc + Alliance disease ingest

---

README.md
docs/index.md
docs/kozathon/setup.md
docs/tutorials/add-documentation.md
docs/tutorials/configure-ingest.md
docs/tutorials/implement-ingest.md
docs/tutorials/test-ingest.md
docs/tutorials/validate-output.md
mkdocs.yml
monarch_ingest/alliance/gene_information.yaml
poetry.lock
pyproject.toml

Also added some navigation to tutorial doc and made a small fix to the Alliance gene load.

Added Kozathon setup doc

---

Makefile
docs/kozathon/setup.md

updated makefile to install requirments | update setup.md for kozathon to use curl instead of wget

Kozathon setup changes

---

docs/kozathon/setup.md

Some small fixes to kozathon docs

---

monarch_ingest/xenbase/gene_information.py
monarch_ingest/zfin/gene2publication.py
monarch_ingest/zfin/gene2publication.yaml
tests/unit/zfin/test_zfin_gene2literature.py

started ingest files for ZFIN gene2publication association.

Creating gene2publication files from ZFIN.

---

download.yaml
monarch_ingest/alliance/gene.yaml
monarch_ingest/alliance/gene_to_disease.yaml
monarch_ingest/alliance/gene_to_phenotype.yaml
monarch_ingest/alliance/publication.yaml
monarch_ingest/flybase/gene_to_publication.yaml
monarch_ingest/hgnc/gene.yaml
monarch_ingest/ingest_pipeline.py
monarch_ingest/maps/alliance-gene.yaml
monarch_ingest/maps/eqe2zp.yaml
monarch_ingest/maps/genepage-2-gene.yaml
monarch_ingest/maps/rgd-gene.yaml
monarch_ingest/pombase/gene.yaml
monarch_ingest/pombase/gene_to_phenotype.yaml
monarch_ingest/rgd/gene_to_publication.yaml
monarch_ingest/sgd/gene_to_publication.yaml
monarch_ingest/xenbase/gene.yaml
monarch_ingest/xenbase/gene_to_phenotype.yaml
monarch_ingest/xenbase/gene_to_publication.yaml
monarch_ingest/zfin/gene_to_phenotype.yaml
monarch_ingest/zfin/gene_to_publication.yaml
poetry.lock
pyproject.toml
workspace.yaml

This adds download support (via a dependency on a very preliminary kghub-downloader repo) into the ingest pipeline.

Initial downloader

---

download.yaml
merge.yaml
monarch_ingest/ingest_pipeline.py
poetry.lock

Mostly re-org of the download destinations and pointing at a slightly newer version of the downloader code

Minor changes from getting the ingest to run on gcp

---

docs/kozathon/setup.md
docs/tutorials/configure-ingest.md
docs/tutorials/validate-output.md
mkdocs.yml
poetry.lock
pyproject.toml
tests/unit/mgi/test_mgi_publication_to_gene.py

Update to the latest downloader and update tutorials to use download cli & simpler koza cli arguments

tutorial docs update + use latest downloader 

---

docs/ingests/ctd.md
download.yaml
mkdocs.yml
monarch_ingest/ctd/chemical_to_disease.py
monarch_ingest/ctd/chemical_to_disease.yaml
monarch_ingest/ingest_pipeline.py
tests/unit/ctd/test_ctd_chemical_to_disease.py
tests/unit/mgi/test_mgi_publication_to_gene.py
tests/unit/zfin/test_zfin_publication_to_gene.py

To give us a starting place for next week, I think this is a faithful reproduction of the one part of the dipper ingest that actually seemed to be running still.

CTD Chemical to Disease ingest

---

monarch_ingest/ctd/chemical_to_disease.py
monarch_ingest/goa/go_annotation.py
monarch_ingest/pombase/gene.py
monarch_ingest/reactome/gene_to_pathway.py
monarch_ingest/rgd/publication_to_gene.yaml
poetry.lock
pyproject.toml
tests/unit/ctd/test_ctd_chemical_to_disease.py
tests/unit/goa/test_go_annotation.py

Until we're confident in the our predicate choice here, let's leave these out.

Exclude marker/mechanism rows from ctd_chemical_to_disease

---

monarch_ingest/goa/go_annotation.py
monarch_ingest/string/protein_links.py

Some tweaks to STRING (reporting missing PID Entrez mappings) and GOA (indentation bug)

String and goa mappings

---

docs/Sources/Dictybase.md
monarch_ingest/ingests/dictybase/gene.py
monarch_ingest/ingests/dictybase/gene.yaml
monarch_ingest/ingests/dictybase/gene_to_phenotype.py
monarch_ingest/ingests/dictybase/utils.py
tests/unit/dictybase/test_dictybase_gene.py
tests/unit/dictybase/test_dictybase_gene_to_phenotype.py

Implemented an independent Dictybase Gene ingest

---

monarch_ingest/cli_utils.py
monarch_ingest/main.py
poetry.lock
pyproject.toml

Now running monarch-gene-mapping to generate mapping files, and using cat merge to rewire edges.

Add & apply gene mapping 

---

docs/Sources/HPOA.md
monarch_ingest/ingests/hpoa/disease_phenotype.py
monarch_ingest/ingests/hpoa/disease_phenotype.yaml
monarch_ingest/ingests/hpoa/hpoa-translation.yaml
tests/unit/hpoa/test_hpoa_disease_phenotype.py

.. also cleaned up some ambiguities in the ingest including basic unit tests and documentation of 'filtered out' phenotype.hpoa Aspects.

Resolves Issue 268 enable negated edges in hpoa ingest

---

monarch_ingest/cli_utils.py
monarch_ingest/download.yaml
poetry.lock
pyproject.toml

Upgraded cat-merge and add mondo disease mappings

---

monarch_ingest/cli_utils.py
monarch_ingest/download.yaml
monarch_ingest/ingests.yaml
monarch_ingest/ingests/goa/go_annotation.py

Change phenio transform read_csv options, used drop rather than subsetting (not sure if this matters? maybe better for memory?)

Phenio transform fix, any any other fixes necessary to get the release working

---

Jenkinsfile-download

Tiny tweak to keep us from uploading everything to data-cache/data/...

Fix data-cache upload command to avoid an extra nested directory

---

Jenkinsfile
poetry.lock
pyproject.toml

This handles the sqlite incompatibility by using Petl for all of the joins and leaving out sqlite.

Update closurizer, fix a couple of typos in the Jenkinsfile

---

monarch_ingest/download.yaml
monarch_ingest/ingests.yaml
monarch_ingest/ingests/xenbase/non_entrez_orthologs.py
monarch_ingest/ingests/xenbase/non_entrez_orthologs.yaml
monarch_ingest/ingests/xenbase/orthologs.py
monarch_ingest/ingests/xenbase/orthologs.yaml
tests/unit/xenbase/test_xenbase_non_entrez_orthologs.py
tests/unit/xenbase/test_xenbase_orthologs.py

Resolves issue #109 - Xenobase orthology

Issue 109 xenbase orthology

---

monarch_ingest/download.yaml
monarch_ingest/ingests/alliance/gene.yaml

Also remove non(never?)-functional xenbase alliance expression file from download.yaml

Update alliance gene to include split up xenbase genes

---

poetry.lock
pyproject.toml

update gene mapping to latest

---

Jenkinsfile-download
monarch_ingest/cli_utils.py
monarch_ingest/download.yaml
monarch_ingest/helper.py
monarch_ingest/main.py

Also adds monarch gene mapping to downloads.yaml

Let Phenio use --force

---

Jenkinsfile
Jenkinsfile-download
monarch_ingest/cli_utils.py
monarch_ingest/main.py
pyproject.toml

(ignore branch name, I just forgot to make a new one)

Update jenkins jobs to reflect recent changes

---

Jenkinsfile
monarch_ingest/cli_utils.py
monarch_ingest/main.py

Leaving this as a draft right now, because I realized that I'd really rather be able to do `ingest sqlite` locally to make the sqlite db rather than having to copy and paste out of the jenkinsfile

Sqlite artifact / Jenkinsfile tweaks

---

monarch_ingest/download.yaml
monarch_ingest/ingests.yaml
monarch_ingest/ingests/panther/genome_orthologs.py
monarch_ingest/ingests/panther/genome_orthologs.yaml
monarch_ingest/ingests/panther/orthology_utils.py
tests/unit/panther/test_genome_orthologs.py
tests/unit/panther/test_ref_genome_orthologs.py

Resolves issue https://github.com/monarch-initiative/monarch-ingest/issues/343

Extending Panther ingest to additional species

---

monarch_ingest/download.yaml
monarch_ingest/ingests/string/protein_links.yaml
tests/unit/string/test_string_protein_links.py

Updated species in STRING ingest

---

monarch_ingest/cli_utils.py
monarch_ingest/main.py

Update to prefer sh over subprocess.call (which seems to lose the output, for better or worse)
Update name of the denormalized edge file to match the output of closurizer

Update to solr ingest/run

---

.github/workflows/test.yml
Makefile
README.md
docs/index.md
monarch_ingest/cli_utils.py
monarch_ingest/ingests/goa/go_annotation.py
monarch_ingest/ingests/goa/go_annotation.yaml
monarch_ingest/ingests/panther/genome_orthologs.py
monarch_ingest/main.py
monarch_ingest/utils/ingest_utils.py
monarch_ingest/utils/log_utils.py
poetry.lock
pyproject.toml

Also includes changes to the pyproject.toml and makefile to reflect updated dependencies, methods, and installation

Update logging (WIP)

---

Jenkinsfile

@caufieldjh Noticed that I needed the node and edge facet properties to be set
I'm going to leave this as a draft until we're sure it's working.

Update kgx graph summary command

---

Jenkinsfile-download
monarch_ingest/cli_utils.py
monarch_ingest/download.yaml
scripts/after_download.sh

- Moved commands that run after download to shell script from Jenkinsfile-download, downloading relation-graph file from phenio
- Unpack phenio relations, pass the new file to closurizer
closes #369

Get relation graph tsv from phenio directly

---

docs/KG-Build-Process/kg-build-process.md

I realized that we really needed a step-by-step overview doc for what we do to build the KG and each of the data artifacts.
I tried to avoid getting too specific, because I don't want it to be wildly wrong in 6 months, but even if it is, I think this should provide a good map of where to find all of the pieces and how they're glued together
closes #430

Adds an overview doc for our kg build process

---

docs/Sources/HPOA.md
src/monarch_ingest/ingests/hpoa/disease_phenotype.py
src/monarch_ingest/ingests/hpoa/disease_phenotype.yaml
src/monarch_ingest/ingests/hpoa/gene_to_phenotype.py
src/monarch_ingest/ingests/hpoa/gene_to_phenotype.yaml
tests/unit/hpoa/test_hpoa_disease_phenotype.py
tests/unit/hpoa/test_hpoa_gene_to_phenotype.py

- Update to hpoa_disease_phenotype for new column names
- update g2p and docs

hpoa column & infores updates

---

src/monarch_ingest/ingests/hpoa/gene_to_disease.py
src/monarch_ingest/ingests/hpoa/gene_to_disease.yaml

- Point to whole hpoa g2d file rather than subset
- orphanet prefix tweak to align with mondo sssom

hpoa g2d fix

---

Jenkinsfile
scripts/kgx_transforms.sh

add kgx transforms to get jsonl and nt output of the full graph

---

.github/workflows/pages.yaml
pyproject.toml

Fix docs not building

---

docs/Sources/CTD.md
src/monarch_ingest/cli_utils.py
src/monarch_ingest/constants.py
src/monarch_ingest/ingests/ctd/chemical_to_disease.py
tests/unit/ctd/test_ctd_chemical_to_disease.py

Update CTD to use affects

---

src/monarch_ingest/ingests/alliance/gene_to_expression.py
src/monarch_ingest/ingests/alliance/gene_to_expression.yaml
tests/unit/alliance/test_alliance_gene_to_expression.py

Clean up evidence/qualifiers for alliance expression

---

README.md

Add documentation badge README.md

---

src/monarch_ingest/cli_utils.py

Swaps the include list for an exclude list. I'm not totally sure why, but EMAPA for example was on the include list but still being excluded, this exclude list seems to actually be working as expected.

Move phenio filtering from an include list to an exclude list to be more permissive

---

scripts/load_sqlite.sh

- Add closure table to sqlite db
- Add closure table to sqlite db, and subject/object indices for edges, denormalized edges and closure table

add closure table to sqlite

---

src/monarch_ingest/ingests/hpoa/gene_to_phenotype.yaml
src/monarch_ingest/ingests/pombase/gene.py
src/monarch_ingest/ingests/pombase/gene.yaml

Fixes column name changes and hardcoded taxon fallback for pombase genes

Fix pombase gene ingest

---

poetry.lock
pyproject.toml
src/monarch_ingest/cli_utils.py
src/monarch_ingest/ingests/alliance/gene.py

A two-item bundle PR. Mostly focused on fixing the artifacts that we generate for Translator, but secondarily fixes the missing taxon info that was causing us to lose yeast genes. 
edit: 3 item, also brings in/fixes cat-merge that was generating data that was incompatible with the dashboard

Fix jsonl/neo4j artifact generation & taxon configuration for alliance gene

---

scripts/after_download.sh

It'll get fixed on the mondo side soon, and we can remove this, but it won't break anything once that's fixed

Add a sed command to fix odd orphanet prefixes

---

docs/Sources/hpoa.md

update primary_knowledge_source in hpoa.md

---

docs/Sources/Phenio.md

This is a work in progress, I will get to it.

Update Phenio.md (again)

---

src/monarch_ingest/ingests/goa/go_annotation.py
src/monarch_ingest/ingests/goa/go_annotation.yaml
src/monarch_ingest/ingests/goa/goa_utils.py
tests/unit/goa/test_go_annotation.py

GOA ingest assigns more meaningful "Primary Knowledge Source" infores identifiers to edges.

issue-426-goa-provenance

---

src/monarch_ingest/cli_utils.py

It's always a challenge to test this step, but I think I got the syntax right.

Upload data dir to monarch-archive

---

docs/Sources/phenio.md

Some time back, on my local computer, the Phenio.md file was fleshed out a bit with content from the Phenio repo. Don't know what inspired it and whether it is useful but over to you, @caufieldjh  and @kevinschaper, for review and a thumbs up or down (or additional refinements before merge).

Flesh out pheno README

---

mkdocs.yaml
src/monarch_ingest/cli_utils.py
src/monarch_ingest/download.yaml
src/monarch_ingest/main.py

Closes #555 
plus some formatting changes

Download mappings from data.mi.org

---

scripts/add_entity_copyfields.sh
scripts/add_fieldtypes.sh
scripts/grounding-fieldtype.json

Adds grounding fieldtype, dynamic field and copyfield declarations to populate it

Adds lowercase keyword grounding field to Solr entity collection

---

scripts/add_entity_copyfields.sh

Quick update of #564 to support the full_name field

Adds copy-field declarations for the full_name field which stores the long name of genes

---

Jenkinsfile
Jenkinsfile-download
src/monarch_ingest/cli_utils.py
src/monarch_ingest/main.py

Write data and package versions to data/output

---

poetry.lock
src/monarch_ingest/cli_utils.py
src/monarch_ingest/utils/log_utils.py

Closes [monarch-app#553](https://github.com/monarch-initiative/monarch-app/issues/553)
Also fixes a few minor typing errors

Upload data to archive bucket on release

---

Jenkinsfile
src/monarch_ingest/cli_utils.py
src/monarch_ingest/utils/export_utils.py

Closes #500 
Would like to get @caufieldjh and @justaddcoffee 's inputs on this PR before merging as well just to be sure. 
In particular, the multi-indexer step was previously the first thing run... this should go _after_ uploading the files, correct?

Fix upload and index to KGHub

---

poetry.lock
pyproject.toml
scripts/load_solr.sh
src/monarch_ingest/cli_utils.py

- **Add output for solr loading, using linkml 1.7 upgrade branch of linkml-solr**
- **upgrade to linkml-solr 1.7**

linkml solr upgrade

---

src/monarch_ingest/ingests/hgnc/gene.py
src/monarch_ingest/ingests/hgnc/gene.yaml

This pull removes dependency on taxon-labels in hgnc ingest code. 
Resolves #597

Removed taxon-labels map requirement from hgnc gene ingest.

---

docs/Sources/go.md
src/monarch_ingest/ingests/go/annotation.py
src/monarch_ingest/ingests/go/annotation.yaml
tests/unit/go/test_go_annotation.py

Pretty straightforward correction of a field that we missed the first time around.

Populate publications for GO annotation ingest, plus update tests & doc to match

---

src/monarch_ingest/utils/ingest_utils.py

Add a couple parentheses where a function call was supposed to be made.

Add missing function call

---

scripts/load_sqlite.sh

This should remove the genotype to phenotype associations that we don't (yet) want in phenio.db, and improve semsimian performance
edit to add: I'm also trying removing phenotype associations with negation-like frequencies of zero.

Updates phenio.db association population to gene & disease phenotype associations

---

src/monarch_ingest/ingests.yaml
src/monarch_ingest/qc_expect.yaml

62k curated orthology edges to zebrafish genes, fresh from the oven!

Add ZFIN orthology ingest

---

scripts/load_solr.sh

Loads from the monarch-app branch with new schema changes that will go into monarch-app once a new KG exists for them

get monarch-app schema from maxo-ui branch

---

src/monarch_ingest/main.py

Fixes issue described in #629 
Adds "--ingest" as an option to *download* and "--ingests" as an option to *transform*.

Brings CLI options for download and transform into parity 

---

scripts/after_download.sh
scripts/generate_reports.sql
scripts/load_solr.sh
scripts/validate_infores.sql
src/monarch_ingest/download.yaml

Validate infores ids in merged kg against registry

---

scripts/after_download.sh
scripts/generate_reports.sql
src/monarch_ingest/cli_utils.py
src/monarch_ingest/download.yaml

- **use infores jsonl release artifact, fix overwrite of node report & counting in node_usage report**
- **fix node id & category in neo4j export**

QC reporting + neo4j node id & category fix
