monarch-initiative/monarch-ingest

download.yaml, merge.yaml, monarch_ingest/ingest_pipeline.py
Fetched from the monarch jenkins server for now as part of the downloads yaml, and brought into the merge. I also removed the filtering based on upstream transforms, since monarch ontology wouldn't end up in the list.
=> Adds the monarch ontology

.github/workflows/test.yml, poetry.lock, pyproject.toml
I wasn't able to run dagster locally due to an odd numpy error, upgrading to 1.22 seems to fix it, but with the down side that numpy 1.22 requires python 3.8 minimum. I don't think that's going to cause any problems for us?
=> Depdency tweaks: numpy to ^1.22, python to ^3.8

docs/ingests/mgi.md, download.yaml, monarch_ingest/ingest_pipeline.py, monarch_ingest/mgi/gene_to_publication.py, monarch_ingest/mgi/gene_to_publication.yaml, monarch_ingest/mgi/metadata.yaml, tests/unit/mgi/test_mgi_gene_to_publication.py
Create ingest of MGI Gene to Publication data. 
Note: this is still on version 0.1.2 of Biolink Model Pydantic. 
When that's updated to latest, we'll want to update all tests/scripts to:
- Change `NamedThingToInformationContentEntityAssociation` to `InformationContentEntityToNamedThingAssociation`
- Switch the order of objects and subjects in "gene_to_publication" ingest files
- Does this make them "publication_to_gene" ingests now? 
- Change `predicate.mentions` to `predicate.mentioned_by`
=> MGI gene to pub ingest

poetry.lock, pyproject.toml
Dependencies that are not needed during runtime are better suited in the `[tool.poetry.dev-dependencies]` section of the `pyproject.toml`.
Doing so makes it possible to exclude those dependencies in the production environment by installing the project via `poetry install --no-dev`.
Furthermore those dev-dependencies doesn't influence the dependencies resolution tree. if other project define `monarch-ingest` as a dependency.
I also updated `pytest` to its latest version, because the current version haven't worked with python3.10.
=> fix: move non-runtime dependencies into dev-dependencies section

download.yaml
The old url 404'd in the downloader
=> update pombase phaf url

monarch_ingest/ingests/omim/gene_to_disease.py, monarch_ingest/ingests/omim/gene_to_disease.yaml, tests/unit/omim/test_omim_gene_disease.py
They should primarily get mapped to HGNC Gene nodes & MONDO disease nodes. We may need to come back and look at the heritable phenotypic markers
=> Remove writing of OMIM nodes

poetry.lock, pyproject.toml
The Biolink Model in the Monarch Ingest is updated to 3.0.1. All unit tests appear to pass as before.
=> Poetry dependency update to Biolink Model 3.0.1

monarch_ingest/main.py
As part of reorganizing the monarch initiative google buckets, updated the destinations for the `release` command
=> update bucket paths in  release command

monarch_ingest/ingests/pombase/gene.yaml
This addresses https://github.com/monarch-initiative/helpdesk/issues/28
=> added filter to only include protein coding genes in pombase gene ingest

monarch_ingest/ingests/bgee/gene_to_expression.yaml
I noticed that in the latest build that the category column was blank for all of bGee. It really would be nice if this whole edge_property thing was less error touchy - definitely something to improve about Koza in the future.
=> Add category to edge_property list for bGee

scripts/add_entity_copyfields.sh, scripts/add_entity_fieldtypes.sh, scripts/load_solr.sh
Closes #296
This is more of a short term solution than long term, but I didn't feel confident about solving this generically in linkml-solr without first making a more concrete solution. 
The ultimate goal here is to give us two new tokenized fields for search & autocomplete matching against the solr index. 
I brought over the field type configuration for both fields from ZFIN. I think the autocomplete field config should be pretty straightforward. The text configuration may need some tweaking, depending on tokenization edge cases. (Do we want to tokenize on word/number boundaries? which punctuation? etc) 
Ultimately, it's probably low stakes until/unless we get genotype names, or find that people have very specific expectations when searching for GO or CHEBI terms with lots of …
=> Solr field types, dynamic fields and copy fields configuration

monarch_ingest/ingests/omim/gene_to_disease.py
This is something that @mbrush spotted and I forgot to write down, and @EvanDietzMorris just noticed again with a check using ORION tools.
=> Flip biolink:risk_affected_by to biolink:affects_risk_for in omim g2d

src/monarch_ingest/cli_utils.py
Starts using the mesh to chebi mappings for ctd ingest. We'll need to actually add it to download.yaml once it's officially in the mapping commons repo. Only adds 334 CTD edges, but that's better than zero.
=> Add mesh to chebi biomappings

Jenkinsfile, neo4j-transform.yaml, scripts/kgx_transforms.sh, src/monarch_ingest/cli_utils.py, src/monarch_ingest/main.py
Doing the kgx tsv to jsonlines conversion in pandas rather than in kgx so that the category closure can be populated in the process. The jsonl files are then used to load into neo4j, which now has complete category labels
fixes #462 
fixes #463
=> Produce jsonl version of graph with category closure populated and load into neo4j artifact

scripts/add_association_copyfields.sh, scripts/add_fieldtypes.sh, scripts/autocomplete-fieldtype.json, scripts/load_solr.sh, scripts/text-fieldtype.json
Refactors the additional solr configuration a bit to put the same field definitions in both entity and association indices, plus adds copy field declarations for association fields relevant to searching the association table from the UI
=> Additional text tokenized association fields

docs/Sources/index.md, mkdocs.yaml
Adds a landing page for the Sources section, mainly so monarch app can link to it without going directly to Alliance
=> add sources landing page

src/monarch_ingest/ingests.yaml, src/monarch_ingest/ingests/dictybase/gene.py, src/monarch_ingest/ingests/ncbi/gene.py
Fixes #490
The dictybase ingest & aspergillus genes from the NCBI ingest were both getting silently skipped when the taxon map lookup failed while getting passed into the pydantic constructor. It didn't halt the ingest in either case, but the loop terminated before a write. I didn't fix the weird silent-ness of the failure at the koza/pydantic level, but I did hard code the taxon names so that the genes come back
=> Fix missing genes happening due to missing taxon info

src/monarch_ingest/cli_utils.py
Just needed to have a version of primary & aggregate knowledge source fields that have a biolink prefix in the field name in the jsonl/neo4j versions of the graph
=> Added extra knowledge source fields for translator

src/monarch_ingest/ingests/panther/orthology_utils.py, tests/unit/panther/test_genome_orthologs.py
This should bring back panther dangling edges connecting to PomBase genes. I think initially the biolink model had the prefix defined as POMBASE, and we shifted our gene & gene to phenotype ingests over, but not this one. 
Fixes #520
=> Update pombase curie prefix in ingest & tests

src/monarch_ingest/ingests/string/protein_links.py, src/monarch_ingest/ingests/string/protein_links.yaml, src/monarch_ingest/ingests/string/string_utils.py, tests/unit/string/test_string_protein_links.py
Maps and returns Evidence and Conclusion codes for evidence type columns with scores > 0. This doesn't completely get to the reviewer's point about ingesting and citing original STRING sources, but it generally highlights the nature of the evidence supporting the STRING statement.
=> Partial resolution of Monarch App issue#393

Jenkinsfile
Use sed to clean out ^M (\r) characters from transform_output & rdf. Koza passes them through just fine, and cat-merge is ok with them, but petl within closurizer treats them as newlines. boo.
=> Add \r scrubbing for transform output and rdf

Jenkinsfile, src/monarch_ingest/cli_utils.py, src/monarch_ingest/data-dump-config.yaml, src/monarch_ingest/main.py, src/monarch_ingest/utils/export_utils.py
This brings forward & updates code from the release-utils repo that exported tsv from solr. I'm happy that using the same code is a great way to have consistent structure in the output from the new graph, but it is a little slow, so we may end up rewriting which backend we export the rows from.
=> Add TSV export, borrowing from release-utils

src/monarch_ingest/cli_utils.py
Allows every node column that comes in via kg-phenio to pass through to the graph. Used to be 100+ columns, now it's a nicely constrained set. The main reason for this change is to allow deprecated in.
=> Keep all phenio node columns

src/monarch_ingest/ingests/reactome/chemical_to_pathway.py, src/monarch_ingest/ingests/reactome/gene_to_pathway.py, src/monarch_ingest/ingests/reactome/pathway.py, tests/unit/reactome/test_reactome_chemical_to_pathway.py, tests/unit/reactome/test_reactome_gene_to_pathway.py, tests/unit/reactome/test_reactome_pathway.py
I don't know that `REACT` is wrong or invalid necessarily, but I know that it's not working with our curie expansion and `Reactome` is, so this seems like a reasonable fix.
=> Update Reactome ingests to use `Reactome` as a prefix rather than `REACT`

scripts/load_sqlite.sh
We were producing phenio.db files with empty term_association tables, this should fix that
=> Update the phenio.db term association population to point to db files in output subdir

src/monarch_ingest/ingests/biogrid/biogrid.py, src/monarch_ingest/ingests/biogrid/biogrid_util.py, src/monarch_ingest/ingests/string/protein_links.py, tests/unit/string/test_string_protein_links.py
Reduce dangling edges for BioGRID by only ingesting genes with prefixes that we reasonably expect we might have
Reduce duplication in StringDB by skipping rows where the same association has already been created in the reverse order
=> Interactions Cleanup

src/monarch_ingest/utils/export_utils.py
Adds the same extra taxon columns for object that subject gets, only if it's a gene to gene association
=> Add object taxon info for gene to gene association export

docs/Sources/hpoa.md, poetry.lock, pyproject.toml, src/monarch_ingest/ingests/hpoa/disease_to_phenotype.py, tests/unit/hpoa/test_hpoa_disease_phenotype.py
- No longer populating publications column with reference value if it's the same as database_id, populating the NCBI urls (will likely require some UI handling). Populating onset qualifier again via a biolink git dependency.
- Documentation update to match code changes
=> Restore onset_qualifier, plus HPOA DB_reference -> publication and doc cleanup

scripts/after_download.sh, src/monarch_ingest/cli_utils.py, src/monarch_ingest/ingests.yaml, src/monarch_ingest/qc_expect.yaml
- **add script fix for mesh: prefix in mondo.sssom.tsv**
- **Adds genotype & variant ingests. Uses ingets.yaml & ingest transform cli code as a way to handle pass-through ingests by configuration. (plus small tweak to mesh->MESH fix).**
=> Add modular genotype & variant ingests

docs/Sources/alliance.md, docs/Sources/hgnc.md, scripts/after_download.sh, src/monarch_ingest/cli_utils.py, src/monarch_ingest/download.yaml, src/monarch_ingest/ingests/alliance/gene.py, src/monarch_ingest/ingests/alliance/gene.yaml, src/monarch_ingest/ingests/alliance/gene_to_phenotype.py, src/monarch_ingest/ingests/hgnc/gene.py, src/monarch_ingest/ingests/hgnc/gene.yaml, src/monarch_ingest/ingests/hpoa/disease_to_phenotype.py, src/monarch_ingest/main.py, src/monarch_ingest/maps/hgnc-so-terms.yaml, src/monarch_ingest/utils/export_utils.py, tests/unit/alliance/test_alliance_gene.py, tests/unit/hgnc/test_hgnc_gene.py, tests/unit/hpoa/test_hpoa_disease_phenotype.py
Adds a lookup table for HGNC to SO term ID to populate the biolink type field for human genes. Also enables the type field for Alliance genes, which was commented out previously. Plus tests.**
Additionally, there are some unrelated formatting changes that came in as well.
Fixes #649
Update to add: The alternate approach would be to create a mapping table from the type strings provided by HGNC directly which in retrospect does sound like it's a little more maintainable. I'm open to rolling this back and going that way instead.
=> Populate type for HGNC & Alliance gene nodes

src/monarch_ingest/ingests/xenbase/orthologs.py, src/monarch_ingest/ingests/xenbase/orthologs.yaml, src/monarch_ingest/qc_expect.yaml, tests/unit/xenbase/test_xenbase_orthologs.py
These edges have been silently dangling the entire time, I think. We don't make XB-GENEPAGE nodes, but we did have the mapping file handy so that we could connect to each of the species. This PR updates the ingests so that each GENEPAGE ID expands to create orthology records for each species entry in the mapping file
=> Map XenBase GenePage orthology records to XB-GENE for each Xenopus species 

src/monarch_ingest/ingests/panther/orthology_utils.py, tests/unit/panther/test_genome_orthologs.py
I created the issue after the fact, so there's a good description here: https://github.com/monarch-initiative/monarch-app/issues/952
=> strip version numbers from ENSEMBL gene IDs in Panther ingest, plus a test
